##
## This file is part of the libsigrokdecode project.
##
## Copyright (C) 2021 Karl Palsson <karlp@etactica.com>
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all
## copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.

from collections import OrderedDict

# Both sets extracted with Tabula and some regexp, not heavily processed further.
regs_atm90e36 = OrderedDict([
(0x00, ('SoftReset', 'Software Reset',)),
(0x01, ('SysStatus0', 'System Status 0',)),
(0x02, ('SysStatus1', 'System Status 1',)),
(0x03, ('FuncEn0', 'Function Enable 0',)),
(0x04, ('FuncEn1', 'Function Enable 1',)),
(0x07, ('ZXConfig', 'Zero-Crossing Configuration',)),
(0x08, ('SagTh', 'Voltage Sag Threshold',)),
(0x09, ('PhaseLossTh', 'Voltage Phase Losing Threshold',)),
(0x0A, ('INWarnTh0', 'Threshold for calculated (Ia + Ib +Ic) N line rms current',)),
(0x0B, ('INWarnTh1', 'Threshold for sampled (from ADC) N line rms current',)),
(0x0C, ('THDNUTh', 'Voltage THD Warning Threshold',)),
(0x0D, ('THDNITh', 'Current THD Warning Threshold',)),
(0x0E, ('DMACtrl', 'DMA Mode Interface Control',)),
(0x0F, ('LastSPIData', 'Last Read/ Write SPI Value',)),
(0x10, ('DetectCtrl', 'Current Detect Control',)),
(0x11, ('DetectTh1', 'Channel 1 current threshold in Detection mode',)),
(0x12, ('DetectTh2', 'Channel 2 current threshold in Detection mode',)),
(0x13, ('DetectTh3', 'Channel 3 current threshold in Detection mode',)),
(0x14, ('PMOffsetA', 'Ioffset for phase A in Partial Measurement mode',)),
(0x15, ('PMOffsetB', 'Ioffset for phase B in Partial Measurement mode',)),
(0x16, ('PMOffsetC', 'Ioffset for phase C in Partial Measurement mode',)),
(0x17, ('PMPGA', 'PGAgain Configuration in Partial Measurement mode',)),
(0x18, ('PMIrmsA', 'Irms for phase A in Partial Measurement mode',)),
(0x19, ('PMIrmsB', 'Irms for phase B in Partial Measurement mode',)),
(0x1A, ('PMIrmsC', 'Irms for phase C in Partial Measurement mode',)),
(0x1B, ('PMConfig', 'Measure configuration in Partial Measurement mode',)),
(0x1C, ('PMAvgSamples', 'Number of 8K samples to be averagedin RMS/mean computation',)),
(0x30, ('ConfigStart', 'Calibration Start Command',)),
(0x31, ('PLconstH', 'High Word of PL_Constant',)),
(0x32, ('PLconstL', 'Low Word of PL_Constant',)),
(0x33, ('MMode0', 'HPF/Integrator On/off CF and all-phase energy computation configuration',)),
(0x34, ('MMode1', 'PGA gain configuration',)),
(0x35, ('PStartTh', 'Active Startup Power Threshold.16 bit unsigned integer, Unit: 0.00032 Watt',)),
(0x36, ('QStartTh', 'Reactive Startup Power Threshold.16 bit unsigned integer, Unit: 0.00032 var',)),
(0x37, ('SStartTh', 'Apparent Startup Power Threshold.16 bit unsigned integer, Unit: 0.00032 VA',)),
(0x38, ('PPhaseTh', 'Startup power threshold (for |P|+|Q| of a phase) for any phase participating Active Energy Accumulation. Common for phase A/B/C.',)),
(0x39, ('QPhaseTh', 'Startup power threshold (for |P|+|Q| of a phase) for any phase participating ReActive Energy Accumulation. Common for phase A/B/C.',)),
(0x3A, ('SPhaseTh', 'Startup power threshold (for |P|+|Q| of a phase) for any phase participating Apparent Energy Accumulation. Common for phase A/B/C.',)),
(0x3B, ('CS0', 'Checksum 0 Checksum register.',)),
(0x40, ('CalStart', 'Calibration Start Command',)),
(0x41, ('POffsetA', 'Phase A Active Power Offset',)),
(0x42, ('QOffsetA', 'Phase A Reactive Power Offset',)),
(0x43, ('POffsetB', 'Phase B Active Power Offset',)),
(0x44, ('QOffsetB', 'Phase B Reactive Power Offset',)),
(0x45, ('POffsetC', 'Phase C Active Power Offset',)),
(0x46, ('QOffsetC', 'Phase C Reactive Power Offset',)),
(0x47, ('GainA', 'Phase A Active/Reactive Energy calibration gain',)),
(0x48, ('PhiA', 'Phase A calibration phase angle',)),
(0x49, ('GainB', 'Phase B Active/Reactive Energy calibration gain',)),
(0x4A, ('PhiB', 'Phase B calibration phase angle',)),
(0x4B, ('GainC', 'Phase C Active/Reactive Energy calibration gain',)),
(0x4C, ('PhiC', 'Phase C calibration phase angle',)),
(0x4D, ('CS1', 'Checksum 1',)),
(0x50, ('HarmStart', 'Harmonic Calibration Startup Command',)),
(0x51, ('POffsetAF', 'Phase A Fundamental Active PowerOffset',)),
(0x52, ('POffsetBF', 'Phase B Fundamental Active PowerOffset',)),
(0x53, ('POffsetCF', 'Phase C Fundamental Active PowerOffset',)),
(0x54, ('PGainAF', 'Phase A Fundamental Active PowerGain',)),
(0x55, ('PGainBF', 'Phase B Fundamental Active PowerGain',)),
(0x56, ('PGainCF', 'Phase C Fundamental Active PowerGain',)),
(0x57, ('CS2', 'Checksum 2',)),
(0x60, ('AdjStart', 'Measurement Calibration Startup Command',)),
(0x61, ('UgainA', 'Phase A Voltage RMS Gain',)),
(0x62, ('IgainA', 'Phase A Current RMS Gain',)),
(0x63, ('UoffsetA', 'Phase A Voltage RMS Offset',)),
(0x64, ('IoffsetA', 'Phase A Current RMS Offset',)),
(0x65, ('UgainB', 'Phase B Voltage RMS Gain',)),
(0x66, ('IgainB', 'Phase B Current RMS Gain',)),
(0x67, ('UoffsetB', 'Phase B Voltage RMS Offset',)),
(0x68, ('IoffsetB', 'Phase B Current RMS Offset',)),
(0x69, ('UgainC', 'Phase C Voltage RMS Gain',)),
(0x6A, ('IgainC', 'Phase C Current RMS Gain',)),
(0x6B, ('UoffsetC', 'Phase C Voltage RMS Offset',)),
(0x6C, ('IoffsetC', 'Phase C Current RMS Offset',)),
(0x6D, ('IgainN', 'Sampled N line Current RMS Gain',)),
(0x6E, ('IoffsetN', 'Sampled N line Current RMS Offset',)),
(0x6F, ('CS3', 'Checksum 3',)),
(0x80, ('APenergyT', 'Total Forward Active Energy',)),
(0x81, ('APenergyA', 'Phase A Forward Active Energy',)),
(0x82, ('APenergyB', 'Phase B Forward Active Energy',)),
(0x83, ('APenergyC', 'Phase C Forward Active Energy',)),
(0x84, ('ANenergyT', 'Total Reverse Active Energy',)),
(0x85, ('ANenergyA', 'Phase A Reverse Active Energy',)),
(0x86, ('ANenergyB', 'Phase B Reverse Active Energy',)),
(0x87, ('ANenergyC', 'Phase C Reverse Active Energy',)),
(0x88, ('RPenergyT', 'Total Forward Reactive Energy',)),
(0x89, ('RPenergyA', 'Phase A Forward Reactive Energy',)),
(0x8A, ('RPenergyB', 'Phase B Forward Reactive Energy',)),
(0x8B, ('RPenergyC', 'Phase C Forward Reactive Energy',)),
(0x8C, ('RNenergyT', 'Total Reverse Reactive Energy',)),
(0x8D, ('RNenergyA', 'Phase A Reverse Reactive Energy',)),
(0x8E, ('RNenergyB', 'Phase B Reverse Reactive Energy',)),
(0x8F, ('RNenergyC', 'Phase C Reverse Reactive Energy',)),
(0x90, ('SAenergyT', 'Total (Arithmetic Sum) Apparent Energy',)),
(0x91, ('SenergyA', 'Phase A Apparent Energy',)),
(0x92, ('SenergyB', 'Phase B Apparent Energy',)),
(0x93, ('SenergyC', 'Phase C Apparent Energy',)),
(0x94, ('SVenergyT', '(Vector Sum) Total Apparent Energy',)),
(0x95, ('EnStatus0', 'Metering Status 0',)),
(0x96, ('EnStatus1', 'Metering Status 1',)),
(0x98, ('SVmeanT', '(Vector Sum) Total Apparent Power',)),
(0x99, ('SVmeanTLSB', 'LSB of (Vector Sum) Total ApparentPower',)),
(0xA0, ('APenergyTF', 'Total Forward Active Fundamental Energy',)),
(0xA1, ('APenergyAF', 'Phase A Forward Active Fundamental Energy',)),
(0xA2, ('APenergyBF', 'Phase B Forward Active Fundamental Energy',)),
(0xA3, ('APenergyCF', 'Phase C Forward Active Fundamental Energy',)),
(0xA4, ('ANenergyTF', 'Total Reverse Active Fundamental Energy',)),
(0xA5, ('ANenergyAF', 'Phase A Reverse Active Fundamental Energy',)),
(0xA6, ('ANenergyBF', 'Phase B Reverse Active Fundamental Energy',)),
(0xA7, ('ANenergyCF', 'Phase C Reverse Active Fundamental Energy',)),
(0xA8, ('APenergyTH', 'Total Forward Active Harmonic Energy',)),
(0xA9, ('APenergyAH', 'Phase A Forward Active Harmonic Energy',)),
(0xAA, ('APenergyBH', 'Phase B Forward Active Harmonic Energy',)),
(0xAB, ('APenergyCH', 'Phase C Forward Active Harmonic Energy',)),
(0xAC, ('ANenergyTH', 'Total Reverse Active Harmonic Energy',)),
(0xAD, ('ANenergyAH', 'Phase A Reverse Active Harmonic Energy',)),
(0xAE, ('ANenergyBH', 'Phase B Reverse Active Harmonic Energy',)),
(0xAF, ('ANenergyCH', 'Phase C Reverse Active Harmonic Energy',)),
(0xB0, ('PmeanT', 'Total (all-phase-sum) Active Power',)),
(0xB1, ('PmeanA', 'Phase A Active Power',)),
(0xB2, ('PmeanB', 'Phase B Active Power',)),
(0xB3, ('PmeanC', 'Phase C Active Power',)),
(0xB4, ('QmeanT', 'Total (all-phase-sum) Reactive Power',)),
(0xB5, ('QmeanA', 'Phase A Reactive Power',)),
(0xB6, ('QmeanB', 'Phase B Reactive Power',)),
(0xB7, ('QmeanC', 'Phase C Reactive Power',)),
(0xB8, ('SAmeanT', 'Total (Arithmetic Sum) apparent power',)),
(0xB9, ('SmeanA', 'phase A apparent power',)),
(0xBA, ('SmeanB', 'phase B apparent power',)),
(0xBB, ('SmeanC', 'phase C apparent power',)),
(0xBC, ('PFmeanT', 'Total power factor',)),
(0xBD, ('PFmeanA', 'phase A power factor',)),
(0xBE, ('PFmeanB', 'phase B power factor',)),
(0xBF, ('PFmeanC', 'phase C power factor',)),
(0xC0, ('PmeanTLSB', 'Lower word of Total (all-phase-sum)',)),
(0xC1, ('PmeanALSB', 'Lower word of Phase A Active Power',)),
(0xC2, ('PmeanBLSB', 'Lower word of Phase B Active Power',)),
(0xC3, ('PmeanCLSB', 'Lower word of Phase C Active Power',)),
(0xC4, ('QmeanTLSB', 'Lower word of Total (all-phase-sum)',)),
(0xC5, ('QmeanALSB', 'Lower word of Phase A Reactive power',)),
(0xC6, ('QmeanBLSB', 'Lower word of Phase B Reactive power',)),
(0xC7, ('QmeanCLSB', 'Lower word of Phase C Reactive power',)),
(0xC8, ('SAmeanTLSB', 'Lower word of Total (Arithmetic Sum)',)),
(0xC9, ('SmeanALSB', 'Lower word of phase A apparent power',)),
(0xCA, ('SmeanBLSB', 'Lower word of phase B apparent power',)),
(0xCB, ('SmeanCLSB', 'Lower word of phase C apparent power',)),
(0xD0, ('PmeanTF', 'Total active fundamental power',)),
(0xD1, ('PmeanAF', 'phase A active fundamental power',)),
(0xD2, ('PmeanBF', 'phase B active fundamental power',)),
(0xD3, ('PmeanCF', 'phase C active fundamental power',)),
(0xD4, ('PmeanTH', 'Total active harmonic power',)),
(0xD5, ('PmeanAH', 'phase A active harmonic power',)),
(0xD6, ('PmeanBH', 'phase B active harmonic power',)),
(0xD7, ('PmeanCH', 'phase C active harmonic power',)),
(0xD8, ('IrmsN1', 'N Line Sampled current RMS',)),
(0xD9, ('UrmsA', 'phase A voltage RMS',)),
(0xDA, ('UrmsB', 'phase B voltage RMS',)),
(0xDB, ('UrmsC', 'phase C voltage RMS',)),
(0xDC, ('IrmsN0', 'N Line calculated current RMS',)),
(0xDD, ('IrmsA', 'phase A current RMS',)),
(0xDE, ('IrmsB', 'phase B current RMS',)),
(0xDF, ('IrmsC', 'phase C current RMS',)),
(0xE0, ('PmeanTFLSB', 'Lower word of Total active fundamental Power',)),
(0xE1, ('PmeanAFLSB', 'Lower word of phase A active fundamental Power',)),
(0xE2, ('PmeanBFLSB', 'Lower word of phase B active fundamental Power',)),
(0xE3, ('PmeanCFLSB', 'Lower word of phase C active fundamental Power',)),
(0xE4, ('PmeanTHLSB', 'Lower word of Total active harmonicPower',)),
(0xE5, ('PmeanAHLSB', 'Lower word of phase A active harmonic Power',)),
(0xE6, ('PmeanBHLSB', 'Lower word of phase B active harmonic Power',)),
(0xE7, ('PmeanCHLSB', 'Lower word of phase C active harmonic Power',)),
(0xE9, ('UrmsALSB', 'Lower word of phase A voltage RMS',)),
(0xEA, ('UrmsBLSB', 'Lower word of phase B voltage RMS',)),
(0xEB, ('UrmsCLSB', 'Lower word of phase C voltage RMS',)),
(0xED, ('IrmsALSB', 'Lower word of phase A current RMS',)),
(0xEE, ('IrmsBLSB', 'Lower word of phase B current RMS',)),
(0xEF, ('IrmsCLSB', 'Lower word of phase C current RMS',)),
(0xF1, ('THDNUA', 'phase A voltage THD+N',)),
(0xF2, ('THDNUB', 'phase B voltage THD+N',)),
(0xF3, ('THDNUC', 'phase C voltage THD+N',)),
(0xF5, ('THDNIA', 'phase A current THD+N',)),
(0xF6, ('THDNIB', 'phase B current THD+N',)),
(0xF7, ('THDNIC', 'phase C current THD+N',)),
(0xF8, ('Freq', 'Frequency',)),
(0xF9, ('PAngleA', 'phase A mean phase angle',)),
(0xFA, ('PAngleB', 'phase B mean phase angle',)),
(0xFB, ('PAngleC', 'phase C mean phase angle',)),
(0xFC, ('Temp', 'Measured temperature',)),
(0xFD, ('UangleA', 'phase A voltage phase angle',)),
(0xFE, ('UangleB', 'phase B voltage phase angle',)),
(0xFF, ('UangleC', 'phase C voltage phase angle',)),
(0x100, ('AI_HR2', 'phase A, Current, Harmonic Ratio for 2 order component',)),
(0x101, ('AI_HR3', 'phase A, Current, Harmonic Ratio for 3 order component',)),
(0x102, ('AI_HR4', 'phase A, Current, Harmonic Ratio for 4 order component',)),
(0x103, ('AI_HR5', 'phase A, Current, Harmonic Ratio for 5 order component',)),
(0x104, ('AI_HR6', 'phase A, Current, Harmonic Ratio for 6 order component',)),
(0x105, ('AI_HR7', 'phase A, Current, Harmonic Ratio for 7 order component',)),
(0x106, ('AI_HR8', 'phase A, Current, Harmonic Ratio for 8 order component',)),
(0x107, ('AI_HR9', 'phase A, Current, Harmonic Ratio for 9 order component',)),
(0x108, ('AI_HR10', 'phase A, Current, Harmonic Ratio for 10 order component',)),
(0x109, ('AI_HR11', 'phase A, Current, Harmonic Ratio for 11 order component',)),
(0x10a, ('AI_HR12', 'phase A, Current, Harmonic Ratio for 12 order component',)),
(0x10b, ('AI_HR13', 'phase A, Current, Harmonic Ratio for 13 order component',)),
(0x10c, ('AI_HR14', 'phase A, Current, Harmonic Ratio for 14 order component',)),
(0x10d, ('AI_HR15', 'phase A, Current, Harmonic Ratio for 15 order component',)),
(0x10e, ('AI_HR16', 'phase A, Current, Harmonic Ratio for 16 order component',)),
(0x10f, ('AI_HR17', 'phase A, Current, Harmonic Ratio for 17 order component',)),
(0x110, ('AI_HR18', 'phase A, Current, Harmonic Ratio for 18 order component',)),
(0x111, ('AI_HR19', 'phase A, Current, Harmonic Ratio for 19 order component',)),
(0x112, ('AI_HR20', 'phase A, Current, Harmonic Ratio for 20 order component',)),
(0x113, ('AI_HR21', 'phase A, Current, Harmonic Ratio for 21 order component',)),
(0x114, ('AI_HR22', 'phase A, Current, Harmonic Ratio for 22 order component',)),
(0x115, ('AI_HR23', 'phase A, Current, Harmonic Ratio for 23 order component',)),
(0x116, ('AI_HR24', 'phase A, Current, Harmonic Ratio for 24 order component',)),
(0x117, ('AI_HR25', 'phase A, Current, Harmonic Ratio for 25 order component',)),
(0x118, ('AI_HR26', 'phase A, Current, Harmonic Ratio for 26 order component',)),
(0x119, ('AI_HR27', 'phase A, Current, Harmonic Ratio for 27 order component',)),
(0x11a, ('AI_HR28', 'phase A, Current, Harmonic Ratio for 28 order component',)),
(0x11b, ('AI_HR29', 'phase A, Current, Harmonic Ratio for 29 order component',)),
(0x11c, ('AI_HR30', 'phase A, Current, Harmonic Ratio for 30 order component',)),
(0x11d, ('AI_HR31', 'phase A, Current, Harmonic Ratio for 31 order component',)),
(0x11E, ('AI_HR32', 'phase A, Current, Harmonic Ratio for 32 order component',)),
(0x11F, ('AI_THD', 'phase A, Current, Total Harmonic Dis-tortion Ratio',)),
(0x120, ('BI_HR2', 'phase B, Current, Harmonic Ratio for 2 order component',)),
(0x121, ('BI_HR3', 'phase B, Current, Harmonic Ratio for 3 order component',)),
(0x122, ('BI_HR4', 'phase B, Current, Harmonic Ratio for 4 order component',)),
(0x123, ('BI_HR5', 'phase B, Current, Harmonic Ratio for 5 order component',)),
(0x124, ('BI_HR6', 'phase B, Current, Harmonic Ratio for 6 order component',)),
(0x125, ('BI_HR7', 'phase B, Current, Harmonic Ratio for 7 order component',)),
(0x126, ('BI_HR8', 'phase B, Current, Harmonic Ratio for 8 order component',)),
(0x127, ('BI_HR9', 'phase B, Current, Harmonic Ratio for 9 order component',)),
(0x128, ('BI_HR10', 'phase B, Current, Harmonic Ratio for 10 order component',)),
(0x129, ('BI_HR11', 'phase B, Current, Harmonic Ratio for 11 order component',)),
(0x12a, ('BI_HR12', 'phase B, Current, Harmonic Ratio for 12 order component',)),
(0x12b, ('BI_HR13', 'phase B, Current, Harmonic Ratio for 13 order component',)),
(0x12c, ('BI_HR14', 'phase B, Current, Harmonic Ratio for 14 order component',)),
(0x12d, ('BI_HR15', 'phase B, Current, Harmonic Ratio for 15 order component',)),
(0x12e, ('BI_HR16', 'phase B, Current, Harmonic Ratio for 16 order component',)),
(0x12f, ('BI_HR17', 'phase B, Current, Harmonic Ratio for 17 order component',)),
(0x130, ('BI_HR18', 'phase B, Current, Harmonic Ratio for 18 order component',)),
(0x131, ('BI_HR19', 'phase B, Current, Harmonic Ratio for 19 order component',)),
(0x132, ('BI_HR20', 'phase B, Current, Harmonic Ratio for 20 order component',)),
(0x133, ('BI_HR21', 'phase B, Current, Harmonic Ratio for 21 order component',)),
(0x134, ('BI_HR22', 'phase B, Current, Harmonic Ratio for 22 order component',)),
(0x135, ('BI_HR23', 'phase B, Current, Harmonic Ratio for 23 order component',)),
(0x136, ('BI_HR24', 'phase B, Current, Harmonic Ratio for 24 order component',)),
(0x137, ('BI_HR25', 'phase B, Current, Harmonic Ratio for 25 order component',)),
(0x138, ('BI_HR26', 'phase B, Current, Harmonic Ratio for 26 order component',)),
(0x139, ('BI_HR27', 'phase B, Current, Harmonic Ratio for 27 order component',)),
(0x13a, ('BI_HR28', 'phase B, Current, Harmonic Ratio for 28 order component',)),
(0x13b, ('BI_HR29', 'phase B, Current, Harmonic Ratio for 29 order component',)),
(0x13c, ('BI_HR30', 'phase B, Current, Harmonic Ratio for 30 order component',)),
(0x13d, ('BI_HR31', 'phase B, Current, Harmonic Ratio for 31 order component',)),
(0x13e, ('BI_HR32', 'phase B, Current, Harmonic Ratio for 32 order component',)),
(0x13F, ('BI_THD', 'phase B, Current, Total Harmonic Dis-tortion Ratio',)),
(0x140, ('CI_HR2', 'phase C, Current, Harmonic Ratio for 2 order component',)),
(0x141, ('CI_HR3', 'phase C, Current, Harmonic Ratio for 3 order component',)),
(0x142, ('CI_HR4', 'phase C, Current, Harmonic Ratio for 4 order component',)),
(0x143, ('CI_HR5', 'phase C, Current, Harmonic Ratio for 5 order component',)),
(0x144, ('CI_HR6', 'phase C, Current, Harmonic Ratio for 6 order component',)),
(0x145, ('CI_HR7', 'phase C, Current, Harmonic Ratio for 7 order component',)),
(0x146, ('CI_HR8', 'phase C, Current, Harmonic Ratio for 8 order component',)),
(0x147, ('CI_HR9', 'phase C, Current, Harmonic Ratio for 9 order component',)),
(0x148, ('CI_HR10', 'phase C, Current, Harmonic Ratio for 10 order component',)),
(0x149, ('CI_HR11', 'phase C, Current, Harmonic Ratio for 11 order component',)),
(0x14a, ('CI_HR12', 'phase C, Current, Harmonic Ratio for 12 order component',)),
(0x14b, ('CI_HR13', 'phase C, Current, Harmonic Ratio for 13 order component',)),
(0x14c, ('CI_HR14', 'phase C, Current, Harmonic Ratio for 14 order component',)),
(0x14d, ('CI_HR15', 'phase C, Current, Harmonic Ratio for 15 order component',)),
(0x14e, ('CI_HR16', 'phase C, Current, Harmonic Ratio for 16 order component',)),
(0x14f, ('CI_HR17', 'phase C, Current, Harmonic Ratio for 17 order component',)),
(0x150, ('CI_HR18', 'phase C, Current, Harmonic Ratio for 18 order component',)),
(0x151, ('CI_HR19', 'phase C, Current, Harmonic Ratio for 19 order component',)),
(0x152, ('CI_HR20', 'phase C, Current, Harmonic Ratio for 20 order component',)),
(0x153, ('CI_HR21', 'phase C, Current, Harmonic Ratio for 21 order component',)),
(0x154, ('CI_HR22', 'phase C, Current, Harmonic Ratio for 22 order component',)),
(0x155, ('CI_HR23', 'phase C, Current, Harmonic Ratio for 23 order component',)),
(0x156, ('CI_HR24', 'phase C, Current, Harmonic Ratio for 24 order component',)),
(0x157, ('CI_HR25', 'phase C, Current, Harmonic Ratio for 25 order component',)),
(0x158, ('CI_HR26', 'phase C, Current, Harmonic Ratio for 26 order component',)),
(0x159, ('CI_HR27', 'phase C, Current, Harmonic Ratio for 27 order component',)),
(0x15a, ('CI_HR28', 'phase C, Current, Harmonic Ratio for 28 order component',)),
(0x15b, ('CI_HR29', 'phase C, Current, Harmonic Ratio for 29 order component',)),
(0x15c, ('CI_HR30', 'phase C, Current, Harmonic Ratio for 30 order component',)),
(0x15d, ('CI_HR31', 'phase C, Current, Harmonic Ratio for 31 order component',)),
(0x15e, ('CI_HR32', 'phase C, Current, Harmonic Ratio for 32 order component',)),
(0x15F, ('CI_THD', 'phase C, Current, Total Harmonic Distortion Ratio',)),
(0x160, ('AV_HR2', 'phase A, Voltage, Harmonic Ratio for 2 order component',)),
(0x161, ('AV_HR3', 'phase A, Voltage, Harmonic Ratio for 3 order component',)),
(0x162, ('AV_HR4', 'phase A, Voltage, Harmonic Ratio for 4 order component',)),
(0x163, ('AV_HR5', 'phase A, Voltage, Harmonic Ratio for 5 order component',)),
(0x164, ('AV_HR6', 'phase A, Voltage, Harmonic Ratio for 6 order component',)),
(0x165, ('AV_HR7', 'phase A, Voltage, Harmonic Ratio for 7 order component',)),
(0x166, ('AV_HR8', 'phase A, Voltage, Harmonic Ratio for 8 order component',)),
(0x167, ('AV_HR9', 'phase A, Voltage, Harmonic Ratio for 9 order component',)),
(0x168, ('AV_HR10', 'phase A, Voltage, Harmonic Ratio for 10 order component',)),
(0x169, ('AV_HR11', 'phase A, Voltage, Harmonic Ratio for 11 order component',)),
(0x16a, ('AV_HR12', 'phase A, Voltage, Harmonic Ratio for 12 order component',)),
(0x16b, ('AV_HR13', 'phase A, Voltage, Harmonic Ratio for 13 order component',)),
(0x16c, ('AV_HR14', 'phase A, Voltage, Harmonic Ratio for 14 order component',)),
(0x16d, ('AV_HR15', 'phase A, Voltage, Harmonic Ratio for 15 order component',)),
(0x16e, ('AV_HR16', 'phase A, Voltage, Harmonic Ratio for 16 order component',)),
(0x16f, ('AV_HR17', 'phase A, Voltage, Harmonic Ratio for 17 order component',)),
(0x170, ('AV_HR18', 'phase A, Voltage, Harmonic Ratio for 18 order component',)),
(0x171, ('AV_HR19', 'phase A, Voltage, Harmonic Ratio for 19 order component',)),
(0x172, ('AV_HR20', 'phase A, Voltage, Harmonic Ratio for 20 order component',)),
(0x173, ('AV_HR21', 'phase A, Voltage, Harmonic Ratio for 21 order component',)),
(0x174, ('AV_HR22', 'phase A, Voltage, Harmonic Ratio for 22 order component',)),
(0x175, ('AV_HR23', 'phase A, Voltage, Harmonic Ratio for 23 order component',)),
(0x176, ('AV_HR24', 'phase A, Voltage, Harmonic Ratio for 24 order component',)),
(0x177, ('AV_HR25', 'phase A, Voltage, Harmonic Ratio for 25 order component',)),
(0x178, ('AV_HR26', 'phase A, Voltage, Harmonic Ratio for 26 order component',)),
(0x179, ('AV_HR27', 'phase A, Voltage, Harmonic Ratio for 27 order component',)),
(0x17a, ('AV_HR28', 'phase A, Voltage, Harmonic Ratio for 28 order component',)),
(0x17b, ('AV_HR29', 'phase A, Voltage, Harmonic Ratio for 29 order component',)),
(0x17c, ('AV_HR30', 'phase A, Voltage, Harmonic Ratio for 30 order component',)),
(0x17d, ('AV_HR31', 'phase A, Voltage, Harmonic Ratio for 31 order component',)),
(0x17e, ('AV_HR32', 'phase A, Voltage, Harmonic Ratio for 32 order component',)),
(0x17F, ('AV_THD', 'phase A, Voltage, Total Harmonic Distortion Ratio',)),
(0x180, ('BV_HR2', 'phase B, Voltage, Harmonic Ratio for 2 order component',)),
(0x181, ('BV_HR3', 'phase B, Voltage, Harmonic Ratio for 3 order component',)),
(0x182, ('BV_HR4', 'phase B, Voltage, Harmonic Ratio for 4 order component',)),
(0x183, ('BV_HR5', 'phase B, Voltage, Harmonic Ratio for 5 order component',)),
(0x184, ('BV_HR6', 'phase B, Voltage, Harmonic Ratio for 6 order component',)),
(0x185, ('BV_HR7', 'phase B, Voltage, Harmonic Ratio for 7 order component',)),
(0x186, ('BV_HR8', 'phase B, Voltage, Harmonic Ratio for 8 order component',)),
(0x187, ('BV_HR9', 'phase B, Voltage, Harmonic Ratio for 9 order component',)),
(0x188, ('BV_HR10', 'phase B, Voltage, Harmonic Ratio for 10 order component',)),
(0x189, ('BV_HR11', 'phase B, Voltage, Harmonic Ratio for 11 order component',)),
(0x18a, ('BV_HR12', 'phase B, Voltage, Harmonic Ratio for 12 order component',)),
(0x18b, ('BV_HR13', 'phase B, Voltage, Harmonic Ratio for 13 order component',)),
(0x18c, ('BV_HR14', 'phase B, Voltage, Harmonic Ratio for 14 order component',)),
(0x18d, ('BV_HR15', 'phase B, Voltage, Harmonic Ratio for 15 order component',)),
(0x18e, ('BV_HR16', 'phase B, Voltage, Harmonic Ratio for 16 order component',)),
(0x18f, ('BV_HR17', 'phase B, Voltage, Harmonic Ratio for 17 order component',)),
(0x190, ('BV_HR18', 'phase B, Voltage, Harmonic Ratio for 18 order component',)),
(0x191, ('BV_HR19', 'phase B, Voltage, Harmonic Ratio for 19 order component',)),
(0x192, ('BV_HR20', 'phase B, Voltage, Harmonic Ratio for 20 order component',)),
(0x193, ('BV_HR21', 'phase B, Voltage, Harmonic Ratio for 21 order component',)),
(0x194, ('BV_HR22', 'phase B, Voltage, Harmonic Ratio for 22 order component',)),
(0x195, ('BV_HR23', 'phase B, Voltage, Harmonic Ratio for 23 order component',)),
(0x196, ('BV_HR24', 'phase B, Voltage, Harmonic Ratio for 24 order component',)),
(0x197, ('BV_HR25', 'phase B, Voltage, Harmonic Ratio for 25 order component',)),
(0x198, ('BV_HR26', 'phase B, Voltage, Harmonic Ratio for 26 order component',)),
(0x199, ('BV_HR27', 'phase B, Voltage, Harmonic Ratio for 27 order component',)),
(0x19a, ('BV_HR28', 'phase B, Voltage, Harmonic Ratio for 28 order component',)),
(0x19b, ('BV_HR29', 'phase B, Voltage, Harmonic Ratio for 29 order component',)),
(0x19c, ('BV_HR30', 'phase B, Voltage, Harmonic Ratio for 30 order component',)),
(0x19d, ('BV_HR31', 'phase B, Voltage, Harmonic Ratio for 31 order component',)),
(0x19e, ('BV_HR32', 'phase B, Voltage, Harmonic Ratio for 32 order component',)),
(0x19F, ('BV_THD', 'phase B, Voltage, Total Harmonic Dis-tortion Ratio',)),
(0x1a0, ('CV_HR2', 'phase C, Voltage, Harmonic Ratio for 2 order component',)),
(0x1a1, ('CV_HR3', 'phase C, Voltage, Harmonic Ratio for 3 order component',)),
(0x1a2, ('CV_HR4', 'phase C, Voltage, Harmonic Ratio for 4 order component',)),
(0x1a3, ('CV_HR5', 'phase C, Voltage, Harmonic Ratio for 5 order component',)),
(0x1a4, ('CV_HR6', 'phase C, Voltage, Harmonic Ratio for 6 order component',)),
(0x1a5, ('CV_HR7', 'phase C, Voltage, Harmonic Ratio for 7 order component',)),
(0x1a6, ('CV_HR8', 'phase C, Voltage, Harmonic Ratio for 8 order component',)),
(0x1a7, ('CV_HR9', 'phase C, Voltage, Harmonic Ratio for 9 order component',)),
(0x1a8, ('CV_HR10', 'phase C, Voltage, Harmonic Ratio for 10 order component',)),
(0x1a9, ('CV_HR11', 'phase C, Voltage, Harmonic Ratio for 11 order component',)),
(0x1aa, ('CV_HR12', 'phase C, Voltage, Harmonic Ratio for 12 order component',)),
(0x1ab, ('CV_HR13', 'phase C, Voltage, Harmonic Ratio for 13 order component',)),
(0x1ac, ('CV_HR14', 'phase C, Voltage, Harmonic Ratio for 14 order component',)),
(0x1ad, ('CV_HR15', 'phase C, Voltage, Harmonic Ratio for 15 order component',)),
(0x1ae, ('CV_HR16', 'phase C, Voltage, Harmonic Ratio for 16 order component',)),
(0x1af, ('CV_HR17', 'phase C, Voltage, Harmonic Ratio for 17 order component',)),
(0x1b0, ('CV_HR18', 'phase C, Voltage, Harmonic Ratio for 18 order component',)),
(0x1b1, ('CV_HR19', 'phase C, Voltage, Harmonic Ratio for 19 order component',)),
(0x1b2, ('CV_HR20', 'phase C, Voltage, Harmonic Ratio for 20 order component',)),
(0x1b3, ('CV_HR21', 'phase C, Voltage, Harmonic Ratio for 21 order component',)),
(0x1b4, ('CV_HR22', 'phase C, Voltage, Harmonic Ratio for 22 order component',)),
(0x1b5, ('CV_HR23', 'phase C, Voltage, Harmonic Ratio for 23 order component',)),
(0x1b6, ('CV_HR24', 'phase C, Voltage, Harmonic Ratio for 24 order component',)),
(0x1b7, ('CV_HR25', 'phase C, Voltage, Harmonic Ratio for 25 order component',)),
(0x1b8, ('CV_HR26', 'phase C, Voltage, Harmonic Ratio for 26 order component',)),
(0x1b9, ('CV_HR27', 'phase C, Voltage, Harmonic Ratio for 27 order component',)),
(0x1ba, ('CV_HR28', 'phase C, Voltage, Harmonic Ratio for 28 order component',)),
(0x1bb, ('CV_HR29', 'phase C, Voltage, Harmonic Ratio for 29 order component',)),
(0x1bc, ('CV_HR30', 'phase C, Voltage, Harmonic Ratio for 30 order component',)),
(0x1bd, ('CV_HR31', 'phase C, Voltage, Harmonic Ratio for 31 order component',)),
(0x1be, ('CV_HR32', 'phase C, Voltage, Harmonic Ratio for 32 order component',)),
(0x1BF, ('CV_THD', 'phase C, Voltage, Total Harmonic Distortion Ratio',)),
(0x1C0, ('AI_FUND', 'phase A, Current, Fundamental component value',)),
(0x1C1, ('AV_FUND', 'phase A, Voltage, Fundamental component value',)),
(0x1C2, ('BI_FUND', 'phase B, Current, Fundamental component value',)),
(0x1C3, ('BV_FUND', 'phase B, Voltage, Fundamental component value',)),
(0x1C4, ('CI_FUND', 'phase C, Current, Fundamental component value',)),
(0x1C5, ('CV_FUND', 'phase C, Voltage, Fundamental component value',)),
(0x1D0, ('DFT_SCALE', 'Input Gain = 2^Scale, i.e. Scale = # of bit shifts[2:0]: Scale for Channel A-I.[5:3]: Scale for Channel B-I.[8:6]: Scale for Channel C-I.[10:9]: Scale for Channel A-V.[12:11]: Scale for Channel B-V.[14:13]: Scale for Channel C-V.[15]: Window disable. ‘1’ disable the Hanning window.',)),
(0x1D1, ('DFT_CTRL', 'Bit[0]: DFT_START.0: Reset and abort the DFT computation.1: Start the DFT. This bit is automatically cleared after DFT finishes.',)),
(0x2f0, ('ChipID', 'Undocumented Chip ID register, see sample code from Atmel',)),
])


regs_atm90e32 = OrderedDict([
(0x00, ('MeterEn', 'Metering Enable',)),
(0x01, ('ChannelMapI', 'Current Channel Mapping Configuration',)),
(0x02, ('ChannelMapU', 'Voltage Channel Mapping Configuration',)),
(0x05, ('SagPeakDetCfg', 'Sag and Peak Detector Period Configuration',)),
(0x06, ('OVth', 'Over Voltage Threshold',)),
(0x07, ('ZXConfig', 'Zero-Crossing Configuration',)),
(0x08, ('SagTh', 'Voltage Sag Threshold',)),
(0x09, ('PhaseLossTh', 'Voltage Phase Losing Threshold',)),
(0x0A, ('InWarnTh', 'Neutral Current (Calculated) Warning Thresh-old',)),
(0x0B, ('OIth', 'Over Current Threshold',)),
(0x0C, ('FreqLoTh', 'Low Threshold for Frequency Detection',)),
(0x0D, ('FreqHiTh', 'High Threshold for Frequency Detection',)),
(0x0E, ('PMPwrCtrl', 'Partial Measurement Mode Power Control',)),
(0x0F, ('IRQ0MergeCfg', 'IRQ0 Merge Configuration',)),
(0x10, ('DetectCtrl', 'Current Detect Control',)),
(0x11, ('DetectTh1', 'Channel1CurrentThresholdinDetectionMode',)),
(0x12, ('DetectTh2', 'Channel2CurrentThresholdinDetectionMode',)),
(0x13, ('DetectTh3', 'Channel3CurrentThresholdinDetectionMode',)),
(0x14, ('IDCoffsetA', 'Phase A Current DC offset',)),
(0x15, ('IDCoffsetB', 'Phase B Current DC offset',)),
(0x16, ('IDCoffsetC', 'Phase C Current DC offset',)),
(0x17, ('UDCoffsetA', 'Voltage DC offset for Channel A',)),
(0x18, ('UDCoffsetB', 'Voltage DC offset for Channel B',)),
(0x19, ('UDCoffsetC', 'Voltage DC offset for Channel C',)),
(0x1A, ('UGainTAB', 'Voltage Gain Temperature Compensation forPhase A/B',)),
(0x1B, ('UGainTC', 'Voltage Gain Temperature Compensation forPhase C',)),
(0x1C, ('PhiFreqComp', 'Phase Compensation for Frequency',)),
(0x20, ('LOGIrms0', 'Current(LogIrms0)Configuration for Segment Compensation',)),
(0x21, ('LOGIrms1', 'Current(LogIrms1)Configuration for Segment Compensation',)),
(0x22, ('F0', 'Nominal Frequency',)),
(0x23, ('T0', 'Nominal Temperature',)),
(0x24, ('PhiAIrms01', 'Phase A Phase Compensation for Current Segment 0 and 1',)),
(0x25, ('PhiAIrms2', 'Phase A Phase Compensation for Current Segment 2',)),
(0x26, ('GainAIrms01', 'Phase A Gain Compensation for Current Segment 0 and 1',)),
(0x27, ('GainAIrms2', 'Phase A Gain Compensation for Current Segment 2',)),
(0x28, ('PhiBIrms01', 'Phase B Phase Compensation for Current Segment 0 and 1',)),
(0x29, ('PhiBIrms2', 'Phase B Phase Compensation for Current Segment 2',)),
(0x2A, ('GainBIrms01', 'Phase B Gain Compensation for Current Segment 0 and 1',)),
(0x2B, ('GainBIrms2', 'Phase B Gain Compensation for Current Segment 2',)),
(0x2C, ('PhiCIrms01', 'Phase C Phase Compensation for Current Segment 0 and 1',)),
(0x2D, ('PhiCIrms2', 'Phase C Phase Compensation for Current Segment 2',)),
(0x2E, ('GainCIrms01', 'Phase C Gain Compensation for Current Segment 0 and 1',)),
(0x2F, ('GainCIrms2', 'Phase C Gain Compensation for Current Segment 2',)),
(0x31, ('PLconstH', 'High Word of PL_Constant',)),
(0x32, ('PLconstL', 'Low Word of PL_Constant',)),
(0x33, ('MMode0', 'Metering Method Configuration',)),
(0x34, ('MMode1', 'PGA Gain Configuration',)),
(0x35, ('PStartTh', 'Active Startup Power Threshold',)),
(0x36, ('QStartTh', 'Reactive Startup Power Threshold',)),
(0x37, ('SStartTh', 'Apparent Startup Power Threshold',)),
(0x38, ('PPhaseTh', 'StartupPowerThresholdforAnyPhase(Active Energy Accumulation)',)),
(0x39, ('QPhaseTh', 'StartupPowerThresholdforAnyPhase(ReActive Energy Accumulation)',)),
(0x3A, ('SPhaseTh', 'StartupPowerThresholdforAnyPhase(Apparent Energy Accumulation)',)),
(0x41, ('PoffsetA', 'Phase A Active Power offset',)),
(0x42, ('QoffsetA', 'Phase A Reactive Power offset',)),
(0x43, ('PoffsetB', 'Phase B Active Power offset',)),
(0x44, ('QoffsetB', 'Phase B Reactive Power offset',)),
(0x45, ('PoffsetC', 'Phase C Active Power offset',)),
(0x46, ('QoffsetC', 'Phase C Reactive Power offset',)),
(0x47, ('PQGainA', 'Phase A Calibration Gain',)),
(0x48, ('PhiA', 'Phase A Calibration Phase Angle',)),
(0x49, ('PQGainB', 'Phase B Calibration Gain',)),
(0x4A, ('PhiB', 'Phase B Calibration Phase Angle',)),
(0x4B, ('PQGainC', 'Phase C Calibration Gain',)),
(0x4C, ('PhiC', 'Phase C Calibration Phase Angle',)),
(0x51, ('PoffsetAF', 'Phase A Fundamental Active Power offset',)),
(0x52, ('PoffsetBF', 'Phase B Fundamental Active Power offset',)),
(0x53, ('PoffsetCF', 'Phase C Fundamental Active Power offset',)),
(0x54, ('PGainAF', 'Phase A Fundamental Calibration Gain',)),
(0x55, ('PGainBF', 'Phase B Fundamental Calibration Gain',)),
(0x56, ('PGainCF', 'Phase C Fundamental Calibration Gain',)),
(0x61, ('UgainA', 'Phase A Voltage RMS Gain',)),
(0x62, ('IgainA', 'Phase A Current RMS Gain',)),
(0x63, ('UoffsetA', 'Phase A Voltage RMS offset',)),
(0x64, ('IoffsetA', 'Phase A Current RMS offset',)),
(0x65, ('UgainB', 'Phase B Voltage RMS Gain',)),
(0x66, ('IgainB', 'Phase B Current RMS Gain',)),
(0x67, ('UoffsetB', 'Phase B Voltage RMS offset',)),
(0x68, ('IoffsetB', 'Phase B Current RMS offset',)),
(0x69, ('UgainC', 'Phase C Voltage RMS Gain',)),
(0x6A, ('IgainC', 'Phase C Current RMS Gain',)),
(0x6B, ('UoffsetC', 'Phase C Voltage RMS offset',)),
(0x6C, ('IoffsetC', 'Phase C Current RMS offset',)),
(0x70, ('SoftReset', 'Software Reset',)),
(0x71, ('EMMState0', 'EMM State 0',)),
(0x72, ('EMMState1', 'EMM State 1',)),
(0x73, ('EMMIntState0', 'EMM Interrupt Status 0',)),
(0x74, ('EMMIntState1', 'EMM Interrupt Status 1',)),
(0x75, ('EMMIntEn0', 'EMM Interrupt Enable 0',)),
(0x76, ('EMMIntEn1', 'EMM Interrupt Enable 1',)),
(0x78, ('LastSPIData', 'Last Read/Write SPI Value',)),
(0x79, ('CRCErrStatus', 'CRC Error Status',)),
(0x7A, ('CRCDigest', 'CRC Digest',)),
(0x7F, ('CfgRegAccEn', 'Configure Register Access Enable',)),
(0x80, ('APenergyT', 'Total Forward Active Energy',)),
(0x81, ('APenergyA', 'Phase A Forward Active Energy',)),
(0x82, ('APenergyB', 'Phase B Forward Active Energy',)),
(0x83, ('APenergyC', 'Phase C Forward Active Energy',)),
(0x84, ('ANenergyT', 'Total Reverse Active Energy',)),
(0x85, ('ANenergyA', 'Phase A Reverse Active Energy',)),
(0x86, ('ANenergyB', 'Phase B Reverse Active Energy',)),
(0x87, ('ANenergyC', 'Phase C Reverse Active Energy',)),
(0x88, ('RPenergyT', 'Total Forward Reactive Energy',)),
(0x89, ('RPenergyA', 'Phase A Forward Reactive Energy',)),
(0x8A, ('RPenergyB', 'Phase B Forward Reactive Energy',)),
(0x8B, ('RPenergyC', 'Phase C Forward Reactive Energy',)),
(0x8C, ('RNenergyT', 'Total Reverse Reactive Energy',)),
(0x8D, ('RNenergyA', 'Phase A Reverse Reactive Energy',)),
(0x8E, ('RNenergyB', 'Phase B Reverse Reactive Energy',)),
(0x8F, ('RNenergyC', 'Phase C Reverse Reactive Energy',)),
(0x90, ('SAenergyT', 'Total (Arithmetic Sum) Apparent Energy',)),
(0x91, ('SenergyA', 'Phase A Apparent Energy',)),
(0x92, ('SenergyB', 'Phase B Apparent Energy',)),
(0x93, ('SenergyC', 'Phase C Apparent Energy',)),
(0xA0, ('APenergyTF', 'Total Forward Active Fundamental Energy',)),
(0xA1, ('APenergyAF', 'Phase A Forward Active Fundamental Energy',)),
(0xA2, ('APenergyBF', 'Phase B Forward Active Fundamental Energy',)),
(0xA3, ('APenergyCF', 'Phase C Forward Active Fundamental Energy',)),
(0xA4, ('ANenergyTF', 'Total Reverse Active Fundamental Energy',)),
(0xA5, ('ANenergyAF', 'Phase A Reverse Active Fundamental Energy',)),
(0xA6, ('ANenergyBF', 'Phase B Reverse Active Fundamental Energy',)),
(0xA7, ('ANenergyCF', 'Phase C Reverse Active Fundamental Energy',)),
(0xA8, ('APenergyTH', 'Total Forward Active Harmonic Energy',)),
(0xA9, ('APenergyAH', 'Phase A Forward Active Harmonic Energy',)),
(0xAA, ('APenergyBH', 'Phase B Forward Active Harmonic Energy',)),
(0xAB, ('APenergyCH', 'Phase C Forward Active Harmonic Energy',)),
(0xAC, ('ANenergyTH', 'Total Reverse Active Harmonic Energy',)),
(0xAD, ('ANenergyAH', 'Phase A Reverse Active Harmonic Energy',)),
(0xAE, ('ANenergyBH', 'Phase B Reverse Active Harmonic Energy',)),
(0xAF, ('ANenergyCH', 'Phase C Reverse Active Harmonic Energy',)),
(0xB0, ('PmeanT', 'Total (all-phase-sum) Active Power',)),
(0xB1, ('PmeanA', 'Phase A Active Power',)),
(0xB2, ('PmeanB', 'Phase B Active Power',)),
(0xB3, ('PmeanC', 'Phase C Active Power',)),
(0xB4, ('QmeanT', 'Total (all-phase-sum) Reactive Power',)),
(0xB5, ('QmeanA', 'Phase A Reactive Power',)),
(0xB6, ('QmeanB', 'Phase B Reactive Power',)),
(0xB7, ('QmeanC', 'Phase C Reactive Power',)),
(0xB8, ('SmeanT', 'Total (Arithmetic Sum) Apparent Power',)),
(0xB9, ('SmeanA', 'Phase A Apparent Power',)),
(0xBA, ('SmeanB', 'Phase B Apparent Power',)),
(0xBB, ('SmeanC', 'Phase C Apparent Power',)),
(0xBC, ('PFmeanT', 'Total Power Factor',)),
(0xBD, ('PFmeanA', 'Phase A Power Factor',)),
(0xBE, ('PFmeanB', 'Phase B Power Factor',)),
(0xBF, ('PFmeanC', 'Phase C Power Factor',)),
(0xC0, ('PmeanTLSB', 'Lower Word of Total (all-phase-sum) ActivePower',)),
(0xC1, ('PmeanALSB', 'Lower Word of Phase A Active Power',)),
(0xC2, ('PmeanBLSB', 'Lower Word of Phase B Active Power',)),
(0xC3, ('PmeanCLSB', 'Lower Word of Phase C Active Power',)),
(0xC4, ('QmeanTLSB', 'Lower Word of Total (all-phase-sum) ReactivePower',)),
(0xC5, ('QmeanALSB', 'Lower Word of Phase A Reactive Power',)),
(0xC6, ('QmeanBLSB', 'Lower Word of Phase B Reactive Power',)),
(0xC7, ('QmeanCLSB', 'Lower Word of Phase C Reactive Power',)),
(0xC8, ('SAmeanTLSB', 'Lower Word of Total (Arithmetic Sum) Apparent Power',)),
(0xC9, ('SmeanALSB', 'Lower Word of Phase A Apparent Power',)),
(0xCA, ('SmeanBLSB', 'Lower Word of Phase B Apparent Power',)),
(0xCB, ('SmeanCLSB', 'Lower Word of Phase C Apparent Power',)),
(0xD0, ('PmeanTF', 'Total Active Fundamental Power',)),
(0xD1, ('PmeanAF', 'Phase A Active Fundamental Power',)),
(0xD2, ('PmeanBF', 'Phase B Active Fundamental Power',)),
(0xD3, ('PmeanCF', 'Phase C Active Fundamental Power',)),
(0xD4, ('PmeanTH', 'Total Active Harmonic Power',)),
(0xD5, ('PmeanAH', 'Phase A Active Harmonic Power',)),
(0xD6, ('PmeanBH', 'Phase B Active Harmonic Power',)),
(0xD7, ('PmeanCH', 'Phase C Active Harmonic Power',)),
(0xD9, ('UrmsA', 'Phase A Voltage RMS',)),
(0xDA, ('UrmsB', 'Phase B Voltage RMS',)),
(0xDB, ('UrmsC', 'Phase C Voltage RMS',)),
(0xDC, ('IrmsN', 'N Line Calculated Current RMS',)),
(0xDD, ('IrmsA', 'Phase A Current RMS',)),
(0xDE, ('IrmsB', 'Phase B Current RMS',)),
(0xDF, ('IrmsC', 'Phase C Current RMS',)),
(0xE0, ('PmeanTFLSB', 'Lower Word of Total Active FundamentalPower',)),
(0xE1, ('PmeanAFLSB', 'Lower Word of Phase A Active FundamentalPower',)),
(0xE2, ('PmeanBFLSB', 'Lower Word of Phase B Active FundamentalPower',)),
(0xE3, ('PmeanCFLSB', 'Lower Word of Phase C Active FundamentalPower',)),
(0xE4, ('PmeanTHLSB', 'Lower Word of Total Active Harmonic Power',)),
(0xE5, ('PmeanAHLSB', 'Lower Word of Phase A Active HarmonicPower',)),
(0xE6, ('PmeanBHLSB', 'Lower Word of Phase B Active HarmonicPower',)),
(0xE7, ('PmeanCHLSB', 'Lower Word of Phase C Active HarmonicPower',)),
(0xE9, ('UrmsALSB', 'Lower Word of Phase A Voltage RMS',)),
(0xEA, ('UrmsBLSB', 'Lower Word of Phase B Voltage RMS',)),
(0xEB, ('UrmsCLSB', 'Lower Word of Phase C Voltage RMS',)),
(0xED, ('IrmsALSB', 'Lower Word of Phase A Current RMS',)),
(0xEE, ('IrmsBLSB', 'Lower Word of Phase B Current RMS',)),
(0xEF, ('IrmsCLSB', 'Lower Word of Phase C Current RMS',)),
(0xF1, ('UPeakA', 'Channel A Voltage Peak',)),
(0xF2, ('UPeakB', 'Channel B Voltage Peak',)),
(0xF3, ('UPeakC', 'Channel C Voltage Peak',)),
(0xF5, ('IPeakA', 'Channel A Current Peak',)),
(0xF6, ('IPeakB', 'Channel B Current Peak',)),
(0xF7, ('IPeakC', 'Channel C Current Peak',)),
(0xF8, ('Freq', 'Frequency',)),
(0xF9, ('PAngleA', 'Phase A Mean Phase Angle',)),
(0xFA, ('PAngleB', 'Phase B Mean Phase Angle',)),
(0xFB, ('PAngleC', 'Phase C Mean Phase Angle',)),
(0xFC, ('Temp', 'Measured Temperature',)),
(0xFD, ('UangleA', 'Phase A Voltage Phase Angle',)),
(0xFE, ('UangleB', 'Phase B Voltage Phase Angle',)),
(0xFF, ('UangleC', 'Phase C Voltage Phase Angle',)),
(0x2f0, ('ChipID', 'Undocumented Chip ID register, see sample code from Atmel',)),
])
